---
# tasks file for while_true_do.srv_tftp

- name: Manage tftp boot Packages
  package:
    name: "{{ wtd_srv_tftp_boot_package }}"
    state: "{{ wtd_srv_tftp_boot_package_state }}"
  become: true
  tags:
    - tftp
    - boot
    - package
    - pxe

# Fedora currently puts the files in /tftpboot instead of /var/lib/tftpboot
- name: Check tftp boot files (Fedora only)
  stat:
    path: "/var/lib/tftpboot/pxelinux.0"
  register: tftpboot_file
  become: true
  when:
    - ansible_distribution == "Fedora"
  tags:
    - tftp
    - boot
    - configuration
    - package
    - pxe

- name: Copy tftp boot files (Fedora only)
  command: "cp -ur /tftpboot/ /var/lib/"
  become: true
  when:
    - ansible_distribution == "Fedora"
    - not tftpboot_file.stat.exists
  tags:
    - tftp
    - boot
    - configuration
    - package
    - pxe

- name: Manage tftp pxelinux.cfg Configuration
  file:
    path: "/var/lib/tftpboot/pxelinux.cfg"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0755
  become: true
  tags:
    - tftp
    - boot
    - configuration
    - pxe

- name: Manage tftp pxelinux.cfg/default Configuration
  template:
    src: "default.j2"
    dest: "/var/lib/tftpboot/pxelinux.cfg/default"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  tags:
    - tftp
    - boot
    - configuration
    - pxe
